-- 01_tables.sql
-- Core tables + constraints (Snowflake notes: NOT NULL + CHECK are enforced; PK/FK/UNIQUE are informational).

USE DATABASE EMP_MGMT_DB;
USE SCHEMA EMP_MGMT;

CREATE OR REPLACE TABLE DEPARTMENTS (
  DEPARTMENT_ID NUMBER(38,0) NOT NULL,
  DEPARTMENT_NAME VARCHAR(100) NOT NULL,
  LOCATION VARCHAR(100),
  CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID),
  CONSTRAINT UQ_DEPT_NAME UNIQUE (DEPARTMENT_NAME)
);

CREATE OR REPLACE TABLE EMPLOYEES (
  EMPLOYEE_ID NUMBER(38,0) NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(100),
  SALARY NUMBER(10,2) NOT NULL,
  DEPARTMENT_ID NUMBER(38,0) NOT NULL,
  HIRE_DATE DATE DEFAULT CURRENT_DATE(),

  CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID),
  CONSTRAINT UQ_EMP_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CK_EMP_SALARY_POSITIVE CHECK (SALARY > 0),
  CONSTRAINT CK_EMP_HIRE_DATE_NOT_FUTURE CHECK (HIRE_DATE <= CURRENT_DATE()),
  CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

CREATE OR REPLACE TABLE SALARY_HISTORY (
  HISTORY_ID NUMBER(38,0) NOT NULL,
  EMPLOYEE_ID NUMBER(38,0) NOT NULL,
  OLD_SALARY NUMBER(10,2),
  NEW_SALARY NUMBER(10,2),
  CHANGE_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  CONSTRAINT PK_SALARY_HISTORY PRIMARY KEY (HISTORY_ID),
  CONSTRAINT FK_SAL_HIST_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

