-- 02_sequences.sql
-- Sequences for surrogate keys.

USE DATABASE EMP_MGMT_DB;
USE SCHEMA EMP_MGMT;

CREATE OR REPLACE SEQUENCE SEQ_EMPLOYEE_ID START = 1001 INCREMENT = 1;
CREATE OR REPLACE SEQUENCE SEQ_SALARY_HISTORY_ID START = 1 INCREMENT = 1;

