-- 03_views.sql
-- Helpful views for reporting and auditing.

USE DATABASE EMP_MGMT_DB;
USE SCHEMA EMP_MGMT;

CREATE OR REPLACE VIEW V_EMPLOYEE_DETAILS AS
SELECT
  e.EMPLOYEE_ID,
  e.FIRST_NAME,
  e.LAST_NAME,
  e.EMAIL,
  e.SALARY,
  e.DEPARTMENT_ID,
  d.DEPARTMENT_NAME,
  d.LOCATION,
  e.HIRE_DATE
FROM EMPLOYEES e
JOIN DEPARTMENTS d
  ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;

CREATE OR REPLACE VIEW V_SALARY_CHANGES AS
SELECT
  h.HISTORY_ID,
  h.EMPLOYEE_ID,
  e.FIRST_NAME,
  e.LAST_NAME,
  h.OLD_SALARY,
  h.NEW_SALARY,
  h.CHANGE_DATE
FROM SALARY_HISTORY h
LEFT JOIN EMPLOYEES e
  ON e.EMPLOYEE_ID = h.EMPLOYEE_ID;

