-- 04_udfs.sql
-- UDFs for calculations / reusability.

USE DATABASE EMP_MGMT_DB;
USE SCHEMA EMP_MGMT;

-- Calculate bonus for an employee given a bonus percent (e.g., 0.15 = 15%)
CREATE OR REPLACE FUNCTION CALCULATE_BONUS(
  P_EMP_ID NUMBER,
  P_BONUS_PERCENT NUMBER
)
RETURNS NUMBER(12,2)
LANGUAGE SQL
AS
$$
  SELECT
    CASE
      WHEN P_BONUS_PERCENT IS NULL OR P_BONUS_PERCENT < 0 THEN NULL
      ELSE ROUND(e.SALARY * P_BONUS_PERCENT, 2)
    END
  FROM EMPLOYEES e
  WHERE e.EMPLOYEE_ID = P_EMP_ID
$$;

-- Get full name for an employee
CREATE OR REPLACE FUNCTION GET_EMP_FULL_NAME(
  P_EMP_ID NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
  SELECT TRIM(e.FIRST_NAME || ' ' || e.LAST_NAME)
  FROM EMPLOYEES e
  WHERE e.EMPLOYEE_ID = P_EMP_ID
$$;

-- Get annual salary (assuming SALARY is monthly) for an employee
CREATE OR REPLACE FUNCTION GET_ANNUAL_SALARY(
  P_EMP_ID NUMBER
)
RETURNS NUMBER(12,2)
LANGUAGE SQL
AS
$$
  SELECT ROUND(e.SALARY * 12, 2)
  FROM EMPLOYEES e
  WHERE e.EMPLOYEE_ID = P_EMP_ID
$$;

-- Classify salary into grade (A/B/C) based on simple thresholds
CREATE OR REPLACE FUNCTION GET_SALARY_GRADE(
  P_SALARY NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
  SELECT
    CASE
      WHEN P_SALARY IS NULL THEN NULL
      WHEN P_SALARY >= 80000 THEN 'A'
      WHEN P_SALARY >= 55000 THEN 'B'
      ELSE 'C'
    END
$$;

-- Department average salary
CREATE OR REPLACE FUNCTION GET_DEPT_AVG_SALARY(
  P_DEPT_ID NUMBER
)
RETURNS NUMBER(12,2)
LANGUAGE SQL
AS
$$
  SELECT ROUND(AVG(e.SALARY), 2)
  FROM EMPLOYEES e
  WHERE e.DEPARTMENT_ID = P_DEPT_ID
$$;

-- Percentage an employee is above/below their department average
CREATE OR REPLACE FUNCTION GET_PCT_ABOVE_DEPT_AVG(
  P_EMP_ID NUMBER
)
RETURNS NUMBER(10,2)
LANGUAGE SQL
AS
$$
  WITH emp AS (
    SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = P_EMP_ID
  ),
  dept AS (
    SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
  )
  SELECT
    CASE
      WHEN d.AVG_SALARY IS NULL OR d.AVG_SALARY = 0 THEN NULL
      ELSE ROUND((e.SALARY - d.AVG_SALARY) / d.AVG_SALARY * 100, 2)
    END
  FROM emp e
  JOIN dept d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
$$;

-- Extract email domain (e.g., example.com) from an email address
CREATE OR REPLACE FUNCTION GET_EMAIL_DOMAIN(
  P_EMAIL VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
  SELECT
    CASE
      WHEN P_EMAIL IS NULL OR POSITION('@' IN P_EMAIL) = 0 THEN NULL
      ELSE SPLIT_PART(P_EMAIL, '@', 2)
    END
$$;

-- Employee tenure in years (fractional), based on HIRE_DATE vs current date
CREATE OR REPLACE FUNCTION GET_TENURE_YEARS(
  P_EMP_ID NUMBER
)
RETURNS NUMBER(10,2)
LANGUAGE SQL
AS
$$
  SELECT
    ROUND(DATEDIFF('day', e.HIRE_DATE, CURRENT_DATE()) / 365.25, 2)
  FROM EMPLOYEES e
  WHERE e.EMPLOYEE_ID = P_EMP_ID
$$;

