-- 06_streams_tasks.sql
-- Trigger-equivalent audit using STREAM + TASK (captures salary changes even from ad-hoc UPDATEs).

USE DATABASE EMP_MGMT_DB;
USE SCHEMA EMP_MGMT;

-- Stream to capture changes to EMPLOYEES
CREATE OR REPLACE STREAM STR_EMPLOYEES_CHANGES
  ON TABLE EMPLOYEES
  SHOW_INITIAL_ROWS = FALSE;

-- Task inserts rows into SALARY_HISTORY when SALARY changes.
-- Note: Tasks require a warehouse. Set it in 00_setup.sql or edit below.
CREATE OR REPLACE TASK TASK_EMP_SALARY_AUDIT
  -- WAREHOUSE = WH_EMP_MGMT
  SCHEDULE = 'USING CRON 0 * * * * UTC'  -- runs hourly; change as needed
  WHEN SYSTEM$STREAM_HAS_DATA('STR_EMPLOYEES_CHANGES')
AS
INSERT INTO SALARY_HISTORY (HISTORY_ID, EMPLOYEE_ID, OLD_SALARY, NEW_SALARY, CHANGE_DATE)
SELECT
  SEQ_SALARY_HISTORY_ID.NEXTVAL AS HISTORY_ID,
  i.EMPLOYEE_ID,
  d.SALARY AS OLD_SALARY,
  i.SALARY AS NEW_SALARY,
  CURRENT_TIMESTAMP() AS CHANGE_DATE
FROM STR_EMPLOYEES_CHANGES i
JOIN STR_EMPLOYEES_CHANGES d
  ON d.METADATA$ROW_ID = i.METADATA$ROW_ID
 AND d.METADATA$ACTION = 'DELETE'
 AND d.METADATA$ISUPDATE = TRUE
WHERE i.METADATA$ACTION = 'INSERT'
  AND i.METADATA$ISUPDATE = TRUE
  AND NVL(d.SALARY, -1) <> NVL(i.SALARY, -1);

-- Start the task (must be resumed once after creation)
ALTER TASK TASK_EMP_SALARY_AUDIT RESUME;

